In [1]:
#-------------------------------------------------------
# Importar paquetes a utilizar
#-------------------------------------------------------
import pandas as pd
import numpy as np 
import networkx as nx
import scipy.stats as stats



#-------------------------------------------------------
# Archivo CSV describiendo los nodos de cada red
#-------------------------------------------------------
ags_nd=pd.read_csv('Gephi_stats/Gephi AGS Stats.csv')             
caba_nd=pd.read_csv('Gephi_stats/Gephi CABA Stats.csv')           #capital
cdmx_nd=pd.read_csv('Gephi_stats/Gephi CDMX Stats.csv')           #capital
gdl_nd=pd.read_csv('Gephi_stats/Gephi GDL Stats.csv') 
hgo_nd=pd.read_csv('Gephi_stats/Gephi Hidalgo Stats.csv')
mad_nd=pd.read_csv('Gephi_stats/Gephi Madrid Stats.csv')          #capital
mtv_nd=pd.read_csv('Gephi_stats/Gephi Montevideo Stats.csv')      #capital
oax_nd=pd.read_csv('Gephi_stats/Gephi Oaxaca Stats.csv')
sao_nd=pd.read_csv('Gephi_stats/Gephi Sao Paulo Stats.csv')       #capital
scl_nd=pd.read_csv('Gephi_stats/Gephi SCL Stats.csv')             #capital


#-------------------------------------------------------
# Archivo CSV describiendo las aristas de cada red
#-------------------------------------------------------
ags_ed=pd.read_csv('Gephi_edges/Gephi AGS Edges.csv')
caba_ed=pd.read_csv('Gephi_edges/Gephi CABA Edges.csv')           #capital
cdmx_ed=pd.read_csv('Gephi_edges/Gephi CDMX Edges.csv')           #capital
gdl_ed=pd.read_csv('Gephi_edges/Gephi GDL Edges.csv')
hgo_ed=pd.read_csv('Gephi_edges/Gephi Hidalgo Edges.csv')
mad_ed=pd.read_csv('Gephi_edges/Gephi Madrid Edges.csv')          #capital
mtv_ed=pd.read_csv('Gephi_edges/Gephi Montevideo Edges.csv')      #capital
oax_ed=pd.read_csv('Gephi_edges/Gephi Oaxaca Edges.csv')
sao_ed=pd.read_csv('Gephi_edges/Gephi Sao Paulo Edges.csv')       #capital
scl_ed=pd.read_csv('Gephi_edges/Gephi SCL Edges.csv')             #capital

In [2]:
def armar_grafo(nodes,edges,rol_str,weight_str):
    '''
    Función con la cual, a partir de una lista de nodos y conexiones, forma un grafo con NetworkX
    
    In:
    - nodes       lista de nodos
    - edges       lista de aristas
    - rol_str     un nombre para el parámetro que describe el rol de un actor
    - weight_str  un nombre para el parámetro que describe el peso de las aristas
    
    Out
    Un objeto NetworkX llamado G.
    '''
    
    #crea un grafo dirigido a partirde la lista edges
    G=nx.from_pandas_edgelist(edges,'Source','Target',edge_attr=["Weight"],create_using=nx.DiGraph())
    
    #rol es un diccionario que manda cada id de un nodo a el atributo correspondiente a rol
    rol = {nid: nodes[nodes['Id']==nid][rol_str].values[0] for nid in nodes['Id']}
    nx.set_node_attributes(G,rol,'rol')
    
    #weight es un diccionario que manda cada id de un nodo a el atributo correspondiente al peso de nodo
    weight = {nid: nodes[nodes['Id']==nid][weight_str].values[0] for nid in nodes['Id']}
    nx.set_node_attributes(G,weight,'weight')
    
    return G

In [3]:
#--------------------------------------------------------------
#Armar grafos a partir de cada uno de los CSV que descargamos
#--------------------------------------------------------------

ags_G=armar_grafo(ags_nd,ags_ed,'role','weight')
caba_G=armar_grafo(caba_nd,caba_ed,'type','weight')
cdmx_G=armar_grafo(cdmx_nd,cdmx_ed,'rol estimado','weight')
gdl_G=armar_grafo(gdl_nd,gdl_ed,'type','weight')
hgo_G=armar_grafo(hgo_nd,hgo_ed,'type','weight')
mad_G=armar_grafo(mad_nd,mad_ed,'rol estimado','weight')
mtv_G=armar_grafo(mtv_nd,mtv_ed,'rol estimado','node size')
oax_G=armar_grafo(oax_nd,oax_ed,'rol','weight')
sao_G=armar_grafo(sao_nd,sao_ed,'rol estimado','weight')
scl_G=armar_grafo(scl_nd,scl_ed,'type','weight')


In [4]:
#---------------------------------------------------------------------------------------------------------------------
# Obtenemos una matriz cuya entrada (i,j) es la fracción de aristas que van de un eje con rol i a un eje con rol j
#---------------------------------------------------------------------------------------------------------------------

rol_map_esp={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}
rol_map_ing={'Knowledge Generator':0,'Enabler':1,'Promoter':2,'Linker':3,'Articulator':4,'Community':5}

capitals={'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}


for capital_str in capitals.keys():
    if capital_str=='Montevideo':
        print('Matriz de artibuto Rol para la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals[capital_str],'rol',mapping=rol_map_ing))
        print('')
        print('')
    else:
        print('Matriz de artibuto Rol para la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals[capital_str],'rol',mapping=rol_map_esp))
        print('')
        print('')

        
        

Matriz de artibuto Rol para la ciudad de CABA

[[0.01508621 0.0387931  0.00862069 0.01724138 0.04741379 0.        ]
 [0.05603448 0.31896552 0.01077586 0.06896552 0.12715517 0.01939655]
 [0.         0.         0.         0.         0.         0.        ]
 [0.00431034 0.05603448 0.00431034 0.03017241 0.0237069  0.01077586]
 [0.01724138 0.05603448 0.         0.01508621 0.03232759 0.        ]
 [0.00215517 0.01508621 0.         0.         0.00431034 0.        ]]


Matriz de artibuto Rol para la ciudad de CDMX

[[0.00398406 0.02390438 0.00199203 0.00199203 0.01195219 0.        ]
 [0.03784861 0.51394422 0.02390438 0.06772908 0.10956175 0.02788845]
 [0.00199203 0.02191235 0.00398406 0.         0.         0.        ]
 [0.00199203 0.02988048 0.         0.00199203 0.00398406 0.00199203]
 [0.00199203 0.01992032 0.         0.00199203 0.00796813 0.00398406]
 [0.         0.05179283 0.0059761  0.0059761  0.00398406 0.00398406]]


Matriz de artibuto Rol para la ciudad de Santiago de Chile

[[0.        

In [5]:
#----------------------
# Subgrafos Nucleares 
#----------------------
#    Obtenemos los -core- nodes (nodos núcleo) de cada una de las redes capitales, 
#    donde el grado total de un nodo núcleo es al menos 3

caba_core=nx.k_core(caba_G,k=3)
cdmx_core=nx.k_core(cdmx_G,k=3)
scl_core=nx.k_core(scl_G,k=3)
mad_core=nx.k_core(mad_G,k=3)
mtv_core=nx.k_core(mtv_G,k=3)
sao_core=nx.k_core(sao_G,k=3)

#----------------------
# GraphMLs Nucleares
#----------------------
#    Ahora, convertimos cada uno de los subgrafos nucleares que obtuvimos
#    en un archivo .graphml

nx.write_graphml(caba_core,'Gephi_core/CABA core graph.graphml')
nx.write_graphml(cdmx_core,'Gephi_core/CDMX core graph.graphml')
nx.write_graphml(scl_core,'Gephi_core/Scl core graph.graphml')
nx.write_graphml(mad_core,'Gephi_core/Mad core graph.graphml')
nx.write_graphml(mtv_core,'Gephi_core/Mtv core graph.graphml')
nx.write_graphml(sao_core,'Gephi_core/Sao core graph.graphml')

#----------------------
# Subgrafos Corteza 
#----------------------
#    Obtenemos los -crust- nodes (nodos corteza) de cada una de las redes capitales, 
#    donde el grado total de un nodo corteza es menor a 3

caba_crust=nx.k_crust(caba_G,k=3)
cdmx_crust=nx.k_crust(cdmx_G,k=3)
scl_crust=nx.k_crust(scl_G,k=3)
mad_crust=nx.k_crust(mad_G,k=3)
mtv_crust=nx.k_crust(mtv_G,k=3)
sao_crust=nx.k_crust(sao_G,k=3)

#----------------------
# GraphMLs Corteza  
#----------------------
#    Ahora, convertimos cada uno de los subgrafos corteza que obtuvimos
#    en un archivo .graphml

nx.write_graphml(caba_crust,'Gephi_crust/CABA crust graph.graphml')
nx.write_graphml(cdmx_crust,'Gephi_crust/CDMX crust graph.graphml')
nx.write_graphml(scl_crust,'Gephi_crust/Scl crust graph.graphml')
nx.write_graphml(mad_crust,'Gephi_crust/Mad crust graph.graphml')
nx.write_graphml(mtv_crust,'Gephi_crust/Mtv crust graph.graphml')
nx.write_graphml(sao_crust,'Gephi_crust/Sao crust graph.graphml')

In [6]:
#------------------------------------------------
#  Core Attribute Mixing Matrices
#------------------------------------------------
#     Para cada uno de los grafos corteza que conseguimos, 
#     Obtenemos una matriz cuya entrada (i,j) es la fracción 
#     de aristas que van de un eje con rol i a un eje con rol j


rol_map_esp={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,
             'Vinculador':3,'Articulador':4,'Comunidad':5}

rol_map_ing={'Knowledge Generator':0,'Enabler':1,'Promoter':2,
             'Linker':3,'Articulator':4,'Community':5}

capitals_cores={'CABA': caba_core, 'CDMX':cdmx_core, 'Santiago de Chile': scl_core, 
                'Montevideo': mtv_core, 'Madrid': mad_core, 'Sao Paulo': sao_core}


for capital_str in capitals.keys():
    if capital_str=='Montevideo':
        print('Matriz de artibuto Rol para el núcleo de la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals_cores[capital_str],'rol',mapping=rol_map_ing))
        print('')
        print('')
    else:
        print('Matriz de artibuto Rol para el núcleo de la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals_cores[capital_str],'rol',mapping=rol_map_esp))
        print('')
        print('')


Matriz de artibuto Rol para el núcleo de la ciudad de CABA

[[0.004 0.028 0.004 0.016 0.06  0.   ]
 [0.032 0.276 0.008 0.08  0.192 0.   ]
 [0.    0.    0.    0.    0.    0.   ]
 [0.    0.068 0.    0.024 0.032 0.004]
 [0.016 0.084 0.    0.016 0.044 0.   ]
 [0.004 0.004 0.    0.    0.004 0.   ]]


Matriz de artibuto Rol para el núcleo de la ciudad de CDMX

[[0.         0.04694836 0.         0.         0.02816901 0.        ]
 [0.03755869 0.49765258 0.         0.05633803 0.14084507 0.03286385]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.03286385 0.         0.         0.00469484 0.        ]
 [0.00469484 0.02816901 0.         0.00469484 0.00938967 0.00469484]
 [0.         0.05633803 0.         0.00469484 0.00469484 0.00469484]]


Matriz de artibuto Rol para el núcleo de la ciudad de Santiago de Chile

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.35       0.         0.075      0.16666667 0.00833333]
 [0.         0.

In [7]:
#----------------------------
# Medidas Globales
#----------------------------
#     Ahora obtenemos, para cada una de las capitales, una serie 
#     pandas.core.series.Series, utilizando la función mean(), 
#     con la que obtenemos las siguientes centralidades 
#           - timeset
#           - mentions    
#           - avg strength                    promedio de la fuerza de los nodos
#           - weight                          promedio del peso de los nodos
#           - indegree                        promedio del grado hacia los nodos
#           - outdegree                       promedio del grado fuera de los nodos
#           - Degree                          promedio de in+out
#           - weighted indegree               promedio del grado hacia los nodos con pesos de acuerdo a intensidades
#           - weighted outdegree             promedio del grado fuera de los nodos con pesos de acuerdo a intensidades
#           - Weighted Degree                promedio in+out de acuerdo a intensidades
#           - Eccentricity                   promedio de eccentricidad 
#           - closnesscentrality              
#           - harmonicclosnesscentrality      
#           - betweenesscentrality          
#           - modularity_class                
#           - Authority                       promedio de autoridad de los nodos de acuerdo al aloritmo HITS
#           - Hub                             promedio de Hubs de los nodos de acuerdo al aloritmo HITS
#           - componentnumber                 número de componentes
#           - strongcompnum                  número de componentes fuertemente conectados
#           - clustering                     promedio de coeficiente de clustering
#           - triangles                      
#           - eigencentrality                 promedio de centralidades eigenvectores

capitals_stats={'CABA': caba_nd, 'CDMX':cdmx_nd, 'Santiago de Chile': scl_nd, 
                'Montevideo': mtv_nd, 'Madrid': mad_nd, 'Sao Paulo': sao_nd}


averages={city: stats.mean() for city,stats in capitals_stats.items()}
averages['Sao Paulo']

#caba_avg=caba_nd.mean()
#cdmx_avg=cdmx_nd.mean()
#scl_avg=scl_nd.mean()
#mad_avg=mad_nd.mean()
#mtv_avg=mtv_nd.mean()
#sao_avg=sao_nd.mean()

timeset                              NaN
mentions                        1.800926
avg strength                    3.430669
weight                          1.253704
node size                            NaN
indegree                        1.685185
outdegree                       1.685185
Degree                          3.370370
weighted indegree               5.847222
weighted outdegree              5.847222
Weighted Degree                11.694444
Eccentricity                    6.726852
closnesscentrality              0.238598
harmonicclosnesscentrality      0.266719
betweenesscentrality          357.333333
modularity_class                5.564815
componentnumber                 0.000000
strongcompnum                  92.027778
clustering                      0.129928
Authority                       0.039103
Hub                             0.039103
triangles                       0.916667
eigencentrality                 0.144046
dtype: float64

In [8]:
#let's try with CDMX

city='CDMX'
avg=averages[city]
datafr=avg.copy().to_frame().T
datafr.drop(['timeset'], axis=1, inplace=True)
if 'type' in datafr.columns:
    datafr.drop(['type'], axis=1, inplace=True)

all_columns = datafr.columns.values.tolist()
print(all_columns)
print('')
print('')
print('')
datafr

['mentions', 'avg strength', 'weight', 'indegree', 'outdegree', 'Degree', 'weighted indegree', 'weighted outdegree', 'Weighted Degree', 'clustering', 'Eccentricity', 'closnesscentrality', 'harmonicclosnesscentrality', 'betweenesscentrality', 'modularity_class', 'componentnumber', 'strongcompnum', 'triangles', 'eigencentrality']





mentions  avg strength    weight  indegree  outdegree    Degree  \
0       NaN      3.477388  1.388629  1.829431   1.829431  3.658863   

   weighted indegree  weighted outdegree  Weighted Degree  clustering  \
0           6.481605            6.481605        12.963211     0.07594   

   Eccentricity  closnesscentrality  harmonicclosnesscentrality  \
0      5.622074            0.267067                     0.28932   

   betweenesscentrality  modularity_class  componentnumber  strongcompnum  \
0            420.227425          4.270903              0.0     127.060201   

   triangles  eigencentrality  
0   0.862876         0.104015

In [9]:
countries={'Montevideo':'Uruguay', 'CABA':'Argentina', 'CDMX':'México',
          'Madrid':'España', 'Sao Paulo': 'Brasil', 'Santiago de Chile': 'Chile'}


list_concat=[]
for city,avg in averages.items():
    datafr=avg.copy().to_frame().T
    
    #borramos del set de columnas a aquellos atributos que no son significantes 
    datafr.drop(['timeset', 'componentnumber'], axis=1, inplace=True)
    if 'type' in datafr.columns:
        datafr.drop(['type'], axis=1, inplace=True)
    
    #añadimos datafr a la lista de dataframes que vamos a concatenar
    list_concat.append(datafr)
    
    #añadimos el atributo que corresponde a el nombre de ciudad y país
    datafr.insert(0, 'País', [countries[city]], True) 
    datafr.insert(0, 'Ciudad', [city], True) 

df_concat=pd.concat(list_concat, ignore_index=True)
df_concat

Ciudad       País  mentions  avg strength    weight  indegree  \
0               CABA  Argentina  2.285088      3.244633  1.481579  2.192982   
1               CDMX     México       NaN      3.477388  1.388629  1.829431   
2  Santiago de Chile      Chile  2.097436      3.417211  1.462564  1.974359   
3         Montevideo    Uruguay  4.065657      3.227742       NaN  3.873737   
4             Madrid     España  1.958159      3.518387  1.362343  1.895397   
5          Sao Paulo     Brasil  1.800926      3.430669  1.253704  1.685185   

   outdegree    Degree  weighted indegree  weighted outdegree  ...  \
0   2.192982  4.385965           7.008772            7.008772  ...   
1   1.829431  3.658863           6.481605            6.481605  ...   
2   1.974359  3.948718           6.882051            6.882051  ...   
3   3.873737  7.747475          12.969697           12.969697  ...   
4   1.895397  3.790795           6.430962            6.430962  ...   
5   1.685185  3.370370           5.847222            5.847222  ...   

   modularity_class  Authority       Hub  strongcompnum  clustering  \
0          5.850877   0.036946  0.036946      96.763158    0.148791   
1          4.270903        NaN       NaN     127.060201    0.075940   
2          3.907692   0.040609  0.040609            NaN    0.134037   
3          2.666667        NaN       NaN      67.898990    0.207747   
4          5.050209        NaN       NaN      89.757322    0.120510   
5          5.564815   0.039103  0.039103      92.027778    0.129928   

   triangles  eigencentrality       ego  pageranks  node size  
0   2.434211         0.093111       NaN        NaN        NaN  
1   0.862876         0.104015       NaN        NaN        NaN  
2   2.153846         0.074438  0.133333    0.00392        NaN  
3  11.060606         0.107790       NaN        NaN   2.749495  
4   1.330544         0.065103       NaN        NaN        NaN  
5   0.916667         0.144046       NaN        NaN        NaN  

[6 rows x 25 columns]

In [10]:
df_concat.isnull().sum()

Ciudad                        0
País                          0
mentions                      1
avg strength                  0
weight                        1
indegree                      0
outdegree                     0
Degree                        0
weighted indegree             0
weighted outdegree            0
Weighted Degree               0
Eccentricity                  0
closnesscentrality            0
harmonicclosnesscentrality    0
betweenesscentrality          0
modularity_class              0
Authority                     3
Hub                           3
strongcompnum                 1
clustering                    0
triangles                     0
eigencentrality               0
ego                           5
pageranks                     5
node size                     5
dtype: int64

In [11]:
#Quitar promedios que en la pagina no mencionan que describen una propiedad global del grafo

df_concat=df_concat.drop('closnesscentrality',axis=1)
df_concat=df_concat.drop('harmonicclosnesscentrality',axis=1)
df_concat=df_concat.drop('modularity_class',axis=1)
df_concat=df_concat.drop('triangles',axis=1)
df_concat=df_concat.drop('eigencentrality',axis=1)
df_concat=df_concat.drop('pageranks',axis=1)
df_concat=df_concat.drop('ego',axis=1)
df_concat=df_concat.drop('betweenesscentrality',axis=1)
df_concat=df_concat.drop('Hub',axis=1)


In [12]:
df_concat['weight'][3]=df_concat['node size'][3]
df_concat=df_concat.drop('node size',axis=1)
df_concat=df_concat.drop('strongcompnum',axis=1)
df_concat=df_concat.drop('Authority',axis=1)

/Users/olga/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [13]:
df_concat

Ciudad       País  mentions  avg strength    weight  indegree  \
0               CABA  Argentina  2.285088      3.244633  1.481579  2.192982   
1               CDMX     México       NaN      3.477388  1.388629  1.829431   
2  Santiago de Chile      Chile  2.097436      3.417211  1.462564  1.974359   
3         Montevideo    Uruguay  4.065657      3.227742  2.749495  3.873737   
4             Madrid     España  1.958159      3.518387  1.362343  1.895397   
5          Sao Paulo     Brasil  1.800926      3.430669  1.253704  1.685185   

   outdegree    Degree  weighted indegree  weighted outdegree  \
0   2.192982  4.385965           7.008772            7.008772   
1   1.829431  3.658863           6.481605            6.481605   
2   1.974359  3.948718           6.882051            6.882051   
3   3.873737  7.747475          12.969697           12.969697   
4   1.895397  3.790795           6.430962            6.430962   
5   1.685185  3.370370           5.847222            5.847222   

   Weighted Degree  Eccentricity  clustering  
0        14.017544      4.798246    0.148791  
1        12.963211      5.622074    0.075940  
2        13.764103      5.041026    0.134037  
3        25.939394      4.479798    0.207747  
4        12.861925      6.079498    0.120510  
5        11.694444      6.726852    0.129928

In [41]:
"""
Global characteristics we may compute:

*Diameter  
*Radius
**Average path length
**Transitivity
*Global Efficiency
Modularity
Assortativity Coefficient
Small Worldness


*=   computed already, not defined for direted graph
**=  computed for undirected graph, also defined for directed graph

"""




'\nGlobal characteristics we may compute:\n\n*Diameter  \n*Radius\n**Average path length\n**Transitivity\nGlobal Efficiency\nModularity\nAssortativity Coefficient\nSmall Worldness\n\n\n*=   computed already, not defined for direted graph\n**=  computed for undirected graph, also defined for directed graph\n\n'

In [15]:
#--------------
# Diameter
#--------------
capitals={'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}


print('Ninguno de los grafos que tenemos son fuertemente conectados, entonces sus diámetros son infinitos:')
for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.diameter(graph)))
    except:
        print(city+str(': ')+str(float('inf')))

print('')
print('')
print('')

print('Entonces, convertimos todos los grafos en no dirigidos y obtenemos diámetros: ')
for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.diameter(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

Ninguno de los grafos que tenemos son fuertemente conectados, entonces sus diámetros son infinitos:
CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf



Entonces, convertimos todos los grafos en no dirigidos y obtenemos diámetros: 
CABA: 6
CDMX: 7
Santiago de Chile: 6
Montevideo: 6
Madrid: 8
Sao Paulo: 8


In [16]:
#--------------
# Radius
#--------------
capitals={'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}

#parece que la eccentricidad de cualquier nodo en las redes dirigidas es infinito, 
#por lo que vamos a tornar no dirigidas todas esas redes
for city,graph in capitals.items():
    for i in range(len(nx.nodes(graph))):
        try:
            print(nx.eccentricity(graph,i))
        except:
            None

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.radius(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: 3
CDMX: 4
Santiago de Chile: 3
Montevideo: 3
Madrid: 5
Sao Paulo: 4


In [54]:
capitals = {'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}

#las columnas que vamos a aregar al DataFrame
diameter = [0]*len(capitals)
radius = [0]*len(capitals)
avg_shortest_path_length = [0]*len(capitals)
transitivity = [0]*len(capitals)
global_efficiency = [0]*len(capitals)
modularity = [0]*len(capitals)
deg_assortativity_coefficient = [0]*len(capitals)



for city, graph in capitals.items():
    city_index=df_concat.index[df_concat['Ciudad']==city].tolist()[0]
    
    #conseguimos cada parámetro para esta ciudad
    undirected=nx.to_undirected(graph)
    diameter[city_index] =                     nx.diameter(undirected)
    radius[city_index] =                       nx.radius(undirected)
    avg_shortest_path_length[city_index] =     nx.average_shortest_path_length(undirected)
    transitivity[city_index] =                 nx.transitivity(undirected)
    global_efficiency[city_index] =            nx.global_efficiency(undirected)
    
    #espacio para modularidad
    
    deg_assortativity_coefficient[city_index]= nx.degree_assortativity_coefficient(undirected)
    
df_concat['Diámetro'] = diameter
df_concat['Radio'] = radius
df_concat['Camino más corto promedio'] = avg_shortest_path_length
df_concat['Transitividad'] = transitivity
df_concat['Eficiencia Global'] = global_efficiency
df_concat['Coeficiente de Asortatividad de Grado'] = deg_assortativity_coefficient
df_concat

Ciudad       País  mentions  avg strength    weight  indegree  \
0               CABA  Argentina  2.285088      3.244633  1.481579  2.192982   
1               CDMX     México       NaN      3.477388  1.388629  1.829431   
2  Santiago de Chile      Chile  2.097436      3.417211  1.462564  1.974359   
3         Montevideo    Uruguay  4.065657      3.227742  2.749495  3.873737   
4             Madrid     España  1.958159      3.518387  1.362343  1.895397   
5          Sao Paulo     Brasil  1.800926      3.430669  1.253704  1.685185   

   outdegree    Degree  weighted indegree  weighted outdegree  \
0   2.192982  4.385965           7.008772            7.008772   
1   1.829431  3.658863           6.481605            6.481605   
2   1.974359  3.948718           6.882051            6.882051   
3   3.873737  7.747475          12.969697           12.969697   
4   1.895397  3.790795           6.430962            6.430962   
5   1.685185  3.370370           5.847222            5.847222   

   Weighted Degree  Eccentricity  clustering  Diámetro  Radio  \
0        14.017544      4.798246    0.148791         6      3   
1        12.963211      5.622074    0.075940         7      4   
2        13.764103      5.041026    0.134037         6      3   
3        25.939394      4.479798    0.207747         6      3   
4        12.861925      6.079498    0.120510         8      5   
5        11.694444      6.726852    0.129928         8      4   

   Camino más corto promedio  Transitividad  Eficiencia Global  \
0                   3.355669       0.107392           0.325773   
1                   3.820318       0.050000           0.289320   
2                   3.227544       0.100744           0.338889   
3                   3.081116       0.224523           0.360837   
4                   3.783517       0.081917           0.294653   
5                   4.324031       0.078571           0.266719   

   Coeficiente de Asortatividad de Grado  
0                              -0.253978  
1                              -0.438891  
2                              -0.277995  
3                              -0.064259  
4                              -0.300096  
5                              -0.458713

In [33]:
#Obsevación (no sé muy ien que hacer aquí):
#parece que aunque las graficas dirigidas no sean conexas, el camino 
#más corto promedio si se está pudiendo computar, y nos da un resultado.. menor?

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.average_shortest_path_length(graph)))
        print(city+str(': ')+str(nx.average_shortest_path_length(nx.to_undirected(graph))))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))

CABA: 1.0389520055645722
CABA: 3.355668907952701

CDMX: 0.9519539404278243
CDMX: 3.82031828690714

Santiago de Chile: 1.1408141686492201
Santiago de Chile: 3.227544277028813

Montevideo: 1.5769881556683587
Montevideo: 3.0811157257857764

Madrid: 1.7462290355472734
Madrid: 3.7835167539819277

Sao Paulo: 0.865848406546081
Sao Paulo: 4.324031007751938



In [38]:
#mismo pasa con transitividad

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.transitivity(graph)))
        print(city+str(': ')+str(nx.transitivity(nx.to_undirected(graph))))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))

CABA: 0.04529683885890517
CABA: 0.10739164086687307

CDMX: 0.016150740242261104
CDMX: 0.05

Santiago de Chile: 0.04595959595959596
Santiago de Chile: 0.10074358359318782

Montevideo: 0.13019250253292808
Montevideo: 0.22452327250358828

Madrid: 0.04256080114449213
Madrid: 0.08191653786707882

Sao Paulo: 0.026829268292682926
Sao Paulo: 0.07857142857142857



In [47]:
#eficiencia global solo esta definida para las versiones no dirigidas de nuestras redes

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.global_efficiency(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))

print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.global_efficiency(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf

***

CABA: 0.32577285725335
CDMX: 0.28932026537809863
Santiago de Chile: 0.3388888888889442
Montevideo: 0.3608367943394337
Madrid: 0.29465342622415475
Sao Paulo: 0.266719012755837


In [51]:
#modularidad no está definido?

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.modularity(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))
        
print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.community.modularity(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf

***

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf


In [52]:
#Assortativity coefficient

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.degree_assortativity_coefficient(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))
        
print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.degree_assortativity_coefficient(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: -0.14027483483281894

CDMX: -0.2260240428366605

Santiago de Chile: -0.20519093988322598

Montevideo: -0.02413444189375622

Madrid: -0.23122324687720558

Sao Paulo: -0.18368170666113665


***

CABA: -0.2539782482426901
CDMX: -0.43889050792093515
Santiago de Chile: -0.27799460336687964
Montevideo: -0.06425865639772806
Madrid: -0.3000957821604226
Sao Paulo: -0.45871333872295067


In [58]:
# Small Worldness
#networkx.algorithms.smallworld.random_reference

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.smallworld.random_reference(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))
        
print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        undirected=nx.to_undirected(graph)
        ref=nx.smallworld.random_reference(undirected)
        
        #clustering coefficient ratio
        cluster_und=nx.clustering_coefficient(undirected)
        cluster_ref=nx.clustering_coefficient(ref)
        cluster_ratio=cluster_und/cluster_ref
        
        #characteristic path length ratio
        cpl_und=nx.average_shortest_path_length(undirected)
        cpl_ref=nx.average_shortest_path_length(ref)
        cpl_ratio=cpl_und/cpl_ref
        
        print(city+str(': ')+str(cluster_ratio/cpl_ratio))
    except:
        print(city+str(': ')+str(float('inf')))

#hmm creo que aqui ya no supe muy bien como utilizar el grafo de referencia
#haré un intento más y si quieres ya te voy a pasar el código, Kevin

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf

***

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf
