In [1]:
#-------------------------------------------------------
# Importar paquetes a utilizar
#-------------------------------------------------------
import pandas as pd
import numpy as np 
import networkx as nx
import scipy.stats as stats



#-------------------------------------------------------
# Archivo CSV describiendo los nodos de cada red
#-------------------------------------------------------
ags_nd=pd.read_csv('Gephi_stats/Gephi AGS Stats.csv')             
caba_nd=pd.read_csv('Gephi_stats/Gephi CABA Stats.csv')           #capital
cdmx_nd=pd.read_csv('Gephi_stats/Gephi CDMX Stats.csv')           #capital
gdl_nd=pd.read_csv('Gephi_stats/Gephi GDL Stats.csv') 
hgo_nd=pd.read_csv('Gephi_stats/Gephi Hidalgo Stats.csv')
mad_nd=pd.read_csv('Gephi_stats/Gephi Madrid Stats.csv')          #capital
mtv_nd=pd.read_csv('Gephi_stats/Gephi Montevideo Stats.csv')      #capital
oax_nd=pd.read_csv('Gephi_stats/Gephi Oaxaca Stats.csv')
sao_nd=pd.read_csv('Gephi_stats/Gephi Sao Paulo Stats.csv')       #capital
scl_nd=pd.read_csv('Gephi_stats/Gephi SCL Stats.csv')             #capital


#-------------------------------------------------------
# Archivo CSV describiendo las aristas de cada red
#-------------------------------------------------------
ags_ed=pd.read_csv('Gephi_edges/Gephi AGS Edges.csv')
caba_ed=pd.read_csv('Gephi_edges/Gephi CABA Edges.csv')           #capital
cdmx_ed=pd.read_csv('Gephi_edges/Gephi CDMX Edges.csv')           #capital
gdl_ed=pd.read_csv('Gephi_edges/Gephi GDL Edges.csv')
hgo_ed=pd.read_csv('Gephi_edges/Gephi Hidalgo Edges.csv')
mad_ed=pd.read_csv('Gephi_edges/Gephi Madrid Edges.csv')          #capital
mtv_ed=pd.read_csv('Gephi_edges/Gephi Montevideo Edges.csv')      #capital
oax_ed=pd.read_csv('Gephi_edges/Gephi Oaxaca Edges.csv')
sao_ed=pd.read_csv('Gephi_edges/Gephi Sao Paulo Edges.csv')       #capital
scl_ed=pd.read_csv('Gephi_edges/Gephi SCL Edges.csv')             #capital

In [2]:
def armar_grafo(nodes,edges,rol_str,weight_str):
    '''
    Función con la cual, a partir de una lista de nodos y conexiones, forma un grafo con NetworkX
    
    In:
    - nodes       lista de nodos
    - edges       lista de aristas
    - rol_str     un nombre para el parámetro que describe el rol de un actor
    - weight_str  un nombre para el parámetro que describe el peso de las aristas
    
    Out
    Un objeto NetworkX llamado G.
    '''
    
    #crea un grafo dirigido a partirde la lista edges
    G=nx.from_pandas_edgelist(edges,'Source','Target',edge_attr=["Weight"],create_using=nx.DiGraph())
    
    #rol es un diccionario que manda cada id de un nodo a el atributo correspondiente a rol
    rol = {nid: nodes[nodes['Id']==nid][rol_str].values[0] for nid in nodes['Id']}
    nx.set_node_attributes(G,rol,'rol')
    
    #weight es un diccionario que manda cada id de un nodo a el atributo correspondiente al peso de nodo
    weight = {nid: nodes[nodes['Id']==nid][weight_str].values[0] for nid in nodes['Id']}
    nx.set_node_attributes(G,weight,'weight')
    
    return G

In [3]:
#--------------------------------------------------------------
#Armar grafos a partir de cada uno de los CSV que descargamos
#--------------------------------------------------------------

ags_G=armar_grafo(ags_nd,ags_ed,'role','weight')
caba_G=armar_grafo(caba_nd,caba_ed,'type','weight')
cdmx_G=armar_grafo(cdmx_nd,cdmx_ed,'rol estimado','weight')
gdl_G=armar_grafo(gdl_nd,gdl_ed,'type','weight')
hgo_G=armar_grafo(hgo_nd,hgo_ed,'type','weight')
mad_G=armar_grafo(mad_nd,mad_ed,'rol estimado','weight')
mtv_G=armar_grafo(mtv_nd,mtv_ed,'rol estimado','node size')
oax_G=armar_grafo(oax_nd,oax_ed,'rol','weight')
sao_G=armar_grafo(sao_nd,sao_ed,'rol estimado','weight')
scl_G=armar_grafo(scl_nd,scl_ed,'type','weight')


In [8]:
#---------------------------------------------------------------------------------------------------------------------
# Obtenemos una matriz cuya entrada (i,j) es la fracción de aristas que van de un eje con rol i a un eje con rol j
#---------------------------------------------------------------------------------------------------------------------

rol_map_esp={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}
rol_map_ing={'Knowledge Generator':0,'Enabler':1,'Promoter':2,'Linker':3,'Articulator':4,'Community':5}

capitals={'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}


for capital_str in capitals.keys():
    if capital_str=='Montevideo':
        print('Matriz de artibuto Rol para la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals[capital_str],'rol',mapping=rol_map_ing))
        print('')
        print('')
    else:
        print('Matriz de artibuto Rol para la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals[capital_str],'rol',mapping=rol_map_esp))
        print('')
        print('')

        
        

Matriz de artibuto Rol para la ciudad de CABA

[[0.01508621 0.0387931  0.00862069 0.01724138 0.04741379 0.        ]
 [0.05603448 0.31896552 0.01077586 0.06896552 0.12715517 0.01939655]
 [0.         0.         0.         0.         0.         0.        ]
 [0.00431034 0.05603448 0.00431034 0.03017241 0.0237069  0.01077586]
 [0.01724138 0.05603448 0.         0.01508621 0.03232759 0.        ]
 [0.00215517 0.01508621 0.         0.         0.00431034 0.        ]]


Matriz de artibuto Rol para la ciudad de CDMX

[[0.00398406 0.02390438 0.00199203 0.00199203 0.01195219 0.        ]
 [0.03784861 0.51394422 0.02390438 0.06772908 0.10956175 0.02788845]
 [0.00199203 0.02191235 0.00398406 0.         0.         0.        ]
 [0.00199203 0.02988048 0.         0.00199203 0.00398406 0.00199203]
 [0.00199203 0.01992032 0.         0.00199203 0.00796813 0.00398406]
 [0.         0.05179283 0.0059761  0.0059761  0.00398406 0.00398406]]


Matriz de artibuto Rol para la ciudad de Santiago de Chile

[[0.        

In [6]:
#----------------------
# Subgrafos Nucleares 
#----------------------
#    Obtenemos los -core- nodes (nodos núcleo) de cada una de las redes capitales, 
#    donde el grado total de un nodo núcleo es al menos 3

caba_sin_islas=nx.k_core(caba_G,k=2)
cdmx_sin_islas=nx.k_core(cdmx_G,k=2)
scl_sin_islas=nx.k_core(scl_G,k=2)
mad_sin_islas=nx.k_core(mad_G,k=2)
mtv_sin_islas=nx.k_core(mtv_G,k=2)
sao_sin_islas=nx.k_core(sao_G,k=2)

#----------------------
# GraphMLs Nucleares
#----------------------
#    Ahora, convertimos cada uno de los subgrafos nucleares que obtuvimos
#    en un archivo .graphml

nx.write_graphml(caba_sin_islas,'Gephi_sin_islas/CABA sin islas graph.graphml')
nx.write_graphml(cdmx_sin_islas,'Gephi_sin_islas/CDMX sin islas graph.graphml')
nx.write_graphml(scl_sin_islas,'Gephi_sin_islas/Scl sin islas graph.graphml')
nx.write_graphml(mad_sin_islas,'Gephi_sin_islas/Mad sin islas graph.graphml')
nx.write_graphml(mtv_sin_islas,'Gephi_sin_islas/Mtv sin islas graph.graphml')
nx.write_graphml(sao_sin_islas,'Gephi_sin_islas/Sao sin islas graph.graphml')

In [9]:
#------------------------------------------------
#  Core Attribute Mixing Matrices
#------------------------------------------------
#     Para cada uno de los grafos corteza que conseguimos, 
#     Obtenemos una matriz cuya entrada (i,j) es la fracción 
#     de aristas que van de un eje con rol i a un eje con rol j


rol_map_esp={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,
             'Vinculador':3,'Articulador':4,'Comunidad':5}

rol_map_ing={'Knowledge Generator':0,'Enabler':1,'Promoter':2,
             'Linker':3,'Articulator':4,'Community':5}

capitals_cores={'CABA': caba_sin_islas, 'CDMX':cdmx_sin_islas, 'Santiago de Chile': scl_sin_islas, 
                'Montevideo': mtv_sin_islas, 'Madrid': mad_sin_islas, 'Sao Paulo': sao_sin_islas}


for capital_str in capitals.keys():
    if capital_str=='Montevideo':
        print('Matriz de artibuto Rol para el núcleo de la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals_cores[capital_str],'rol',mapping=rol_map_ing))
        print('')
        print('')
    else:
        print('Matriz de artibuto Rol para el núcleo de la ciudad de '+capital_str)
        print('')
        print(nx.attribute_mixing_matrix(capitals_cores[capital_str],'rol',mapping=rol_map_esp))
        print('')
        print('')


Matriz de artibuto Rol para el núcleo de la ciudad de CABA

[[0.01146132 0.03724928 0.00573066 0.01432665 0.05444126 0.        ]
 [0.04297994 0.28366762 0.00859599 0.0773639  0.14613181 0.01432665]
 [0.         0.         0.         0.         0.         0.        ]
 [0.00573066 0.06876791 0.00573066 0.02292264 0.0286533  0.01432665]
 [0.01432665 0.07163324 0.         0.01719198 0.04011461 0.        ]
 [0.00286533 0.00859599 0.         0.         0.00286533 0.        ]]


Matriz de artibuto Rol para el núcleo de la ciudad de CDMX

[[0.         0.03343465 0.         0.         0.01823708 0.        ]
 [0.03039514 0.48328267 0.01823708 0.0668693  0.12158055 0.02735562]
 [0.         0.01823708 0.00303951 0.         0.         0.        ]
 [0.         0.03951368 0.         0.00303951 0.00607903 0.00303951]
 [0.00303951 0.02431611 0.         0.00303951 0.01215805 0.00303951]
 [0.         0.06382979 0.00303951 0.00607903 0.00607903 0.00303951]]


Matriz de artibuto Rol para el núcleo de la ci

In [12]:
caba_sin_islas_nd=pd.read_csv('Gephi_sin_islas/CABA sin islas nodes.csv')
cdmx_sin_islas_nd=pd.read_csv('Gephi_sin_islas/CDMX sin islas nodes.csv')
mad_sin_islas_nd=pd.read_csv('Gephi_sin_islas/Mad sin islas nodes.csv')
mtv_sin_islas_nd=pd.read_csv('Gephi_sin_islas/Mtv sin islas nodes.csv')
sao_sin_islas_nd=pd.read_csv('Gephi_sin_islas/Sao sin islas nodes.csv')
scl_sin_islas_nd=pd.read_csv('Gephi_sin_islas/Scl sin islas nodes.csv') 

In [13]:
#----------------------------
# Medidas Globales
#----------------------------
#     Ahora obtenemos, para cada una de las capitales, una serie 
#     pandas.core.series.Series, utilizando la función mean(), 
#     con la que obtenemos las siguientes centralidades 
#           - timeset
#           - mentions    
#           - avg strength                    promedio de la fuerza de los nodos
#           - weight                          promedio del peso de los nodos
#           - indegree                        promedio del grado hacia los nodos
#           - outdegree                       promedio del grado fuera de los nodos
#           - Degree                          promedio de in+out
#           - weighted indegree               promedio del grado hacia los nodos con pesos de acuerdo a intensidades
#           - weighted outdegree             promedio del grado fuera de los nodos con pesos de acuerdo a intensidades
#           - Weighted Degree                promedio in+out de acuerdo a intensidades
#           - Eccentricity                   promedio de eccentricidad 
#           - closnesscentrality              
#           - harmonicclosnesscentrality      
#           - betweenesscentrality          
#           - modularity_class                
#           - Authority                       promedio de autoridad de los nodos de acuerdo al aloritmo HITS
#           - Hub                             promedio de Hubs de los nodos de acuerdo al aloritmo HITS
#           - componentnumber                 número de componentes
#           - strongcompnum                  número de componentes fuertemente conectados
#           - clustering                     promedio de coeficiente de clustering
#           - triangles                      
#           - eigencentrality                 promedio de centralidades eigenvectores

capitals_stats={'CABA': caba_sin_islas_nd, 'CDMX':cdmx_sin_islas_nd, 'Santiago de Chile': scl_sin_islas_nd, 
                'Montevideo': mtv_sin_islas_nd, 'Madrid': mad_sin_islas_nd, 'Sao Paulo': sao_sin_islas_nd}


averages={city: stats.mean() for city,stats in capitals_stats.items()}
averages['Sao Paulo']

#caba_avg=caba_nd.mean()
#cdmx_avg=cdmx_nd.mean()
#scl_avg=scl_nd.mean()
#mad_avg=mad_nd.mean()
#mtv_avg=mtv_nd.mean()
#sao_avg=sao_nd.mean()

timeset                              NaN
d1                              1.973626
indegree                        2.362637
outdegree                       2.362637
Degree                          4.725275
Eccentricity                    3.824176
closnesscentrality              0.206611
harmonicclosnesscentrality      0.239699
betweenesscentrality          126.659341
modularity_class                1.945055
clustering                      0.244116
eigencentrality                 0.190468
dtype: float64

In [14]:
#let's try with CDMX

city='CDMX'
avg=averages[city]
datafr=avg.copy().to_frame().T
datafr.drop(['timeset'], axis=1, inplace=True)
if 'type' in datafr.columns:
    datafr.drop(['type'], axis=1, inplace=True)

all_columns = datafr.columns.values.tolist()
print(all_columns)
print('')
print('')
print('')
datafr

['d1', 'indegree', 'outdegree', 'Degree', 'weighted indegree', 'weighted outdegree', 'Weighted Degree', 'Eccentricity', 'closnesscentrality', 'harmonicclosnesscentrality', 'betweenesscentrality', 'modularity_class', 'clustering', 'eigencentrality']





d1  indegree  outdegree    Degree  weighted indegree  \
0  2.307936  2.611111   2.611111  5.222222           2.611111   

   weighted outdegree  Weighted Degree  Eccentricity  closnesscentrality  \
0            2.611111         5.222222      3.619048            0.198771   

   harmonicclosnesscentrality  betweenesscentrality  modularity_class  \
0                    0.225079            156.222222          3.452381   

   clustering  eigencentrality  
0    0.110592         0.179422

In [18]:
countries={'Montevideo':'Uruguay', 'CABA':'Argentina', 'CDMX':'México',
          'Madrid':'España', 'Sao Paulo': 'Brasil', 'Santiago de Chile': 'Chile'}


list_concat=[]
for city,avg in averages.items():
    datafr=avg.copy().to_frame().T
    
    #borramos del set de columnas a aquellos atributos que no son significantes 
    #datafr.drop(['timeset', 'componentnumber'], axis=1, inplace=True)
    if 'type' in datafr.columns:
        datafr.drop(['type'], axis=1, inplace=True)
    
    #añadimos datafr a la lista de dataframes que vamos a concatenar
    list_concat.append(datafr)
    
    #añadimos el atributo que corresponde a el nombre de ciudad y país
    datafr.insert(0, 'País', [countries[city]], True) 
    datafr.insert(0, 'Ciudad', [city], True) 

df_concat=pd.concat(list_concat, ignore_index=True)
df_concat

Ciudad       País  timeset        d1  indegree  outdegree  \
0               CABA  Argentina      NaN  2.279646  3.088496   3.088496   
1               CDMX     México      NaN  2.307936  2.611111   2.611111   
2  Santiago de Chile      Chile      NaN  2.404762  2.928571   2.928571   
3         Montevideo    Uruguay      NaN  4.348214  5.232143   5.232143   
4             Madrid     España      NaN  2.118095  2.733333   2.733333   
5          Sao Paulo     Brasil      NaN  1.973626  2.362637   2.362637   

      Degree  weighted indegree  weighted outdegree  Weighted Degree  \
0   6.176991           3.088496            3.088496         6.176991   
1   5.222222           2.611111            2.611111         5.222222   
2   5.857143                NaN                 NaN              NaN   
3  10.464286                NaN                 NaN              NaN   
4   5.466667           2.733333            2.733333         5.466667   
5   4.725275                NaN                 NaN              NaN   

   Eccentricity  closnesscentrality  harmonicclosnesscentrality  \
0      3.884956            0.377842                    0.412624   
1      3.619048            0.198771                    0.225079   
2      3.809524            0.192974                    0.228054   
3      4.267857            0.277862                    0.312725   
4      5.047619            0.204010                    0.239418   
5      3.824176            0.206611                    0.239699   

   betweenesscentrality  modularity_class  Authority       Hub  clustering  \
0             94.955752          2.769912   0.060898  0.050444         NaN   
1            156.222222          3.452381        NaN       NaN    0.110592   
2            111.666667          2.690476        NaN       NaN    0.220837   
3            164.794643          2.714286        NaN       NaN    0.237409   
4            199.571429          2.447619        NaN       NaN    0.187666   
5            126.659341          1.945055        NaN       NaN    0.244116   

   eigencentrality  
0              NaN  
1         0.179422  
2         0.147363  
3         0.170969  
4         0.198474  
5         0.190468

In [19]:
df_concat.isnull().sum()

Ciudad                        0
País                          0
timeset                       6
d1                            0
indegree                      0
outdegree                     0
Degree                        0
weighted indegree             3
weighted outdegree            3
Weighted Degree               3
Eccentricity                  0
closnesscentrality            0
harmonicclosnesscentrality    0
betweenesscentrality          0
modularity_class              0
Authority                     5
Hub                           5
clustering                    1
eigencentrality               1
dtype: int64

In [24]:
#Quitar promedios que en la pagina no mencionan que describen una propiedad global del grafo

df_concat=df_concat.drop('closnesscentrality',axis=1)
df_concat=df_concat.drop('harmonicclosnesscentrality',axis=1)
df_concat=df_concat.drop('modularity_class',axis=1)
#df_concat=df_concat.drop('triangles',axis=1)
df_concat=df_concat.drop('eigencentrality',axis=1)
#df_concat=df_concat.drop('pageranks',axis=1)
#df_concat=df_concat.drop('ego',axis=1)
df_concat=df_concat.drop('betweenesscentrality',axis=1)
df_concat=df_concat.drop('Hub',axis=1)


In [28]:
#df_concat['weight'][3]=df_concat['node size'][3]
#df_concat=df_concat.drop('node size',axis=1)
#df_concat=df_concat.drop('strongcompnum',axis=1)
df_concat=df_concat.drop('Authority',axis=1)

In [29]:
df_concat

Ciudad       País  timeset        d1  indegree  outdegree  \
0               CABA  Argentina      NaN  2.279646  3.088496   3.088496   
1               CDMX     México      NaN  2.307936  2.611111   2.611111   
2  Santiago de Chile      Chile      NaN  2.404762  2.928571   2.928571   
3         Montevideo    Uruguay      NaN  4.348214  5.232143   5.232143   
4             Madrid     España      NaN  2.118095  2.733333   2.733333   
5          Sao Paulo     Brasil      NaN  1.973626  2.362637   2.362637   

      Degree  weighted indegree  weighted outdegree  Weighted Degree  \
0   6.176991           3.088496            3.088496         6.176991   
1   5.222222           2.611111            2.611111         5.222222   
2   5.857143                NaN                 NaN              NaN   
3  10.464286                NaN                 NaN              NaN   
4   5.466667           2.733333            2.733333         5.466667   
5   4.725275                NaN                 NaN              NaN   

   Eccentricity  clustering  
0      3.884956         NaN  
1      3.619048    0.110592  
2      3.809524    0.220837  
3      4.267857    0.237409  
4      5.047619    0.187666  
5      3.824176    0.244116

In [14]:
"""
Global characteristics we may compute:

*Diameter  
*Radius
**Average path length
**Transitivity
*Global Efficiency
Modularity
Assortativity Coefficient
Small Worldness


*=   computed already, not defined for direted graph
**=  computed for undirected graph, also defined for directed graph

"""




'\nGlobal characteristics we may compute:\n\n*Diameter  \n*Radius\n**Average path length\n**Transitivity\n*Global Efficiency\nModularity\nAssortativity Coefficient\nSmall Worldness\n\n\n*=   computed already, not defined for direted graph\n**=  computed for undirected graph, also defined for directed graph\n\n'

In [15]:
#--------------
# Diameter
#--------------
capitals={'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}


print('Ninguno de los grafos que tenemos son fuertemente conectados, entonces sus diámetros son infinitos:')
for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.diameter(graph)))
    except:
        print(city+str(': ')+str(float('inf')))

print('')
print('')
print('')

print('Entonces, convertimos todos los grafos en no dirigidos y obtenemos diámetros: ')
for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.diameter(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

Ninguno de los grafos que tenemos son fuertemente conectados, entonces sus diámetros son infinitos:
CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf



Entonces, convertimos todos los grafos en no dirigidos y obtenemos diámetros: 
CABA: 6
CDMX: 7
Santiago de Chile: 6
Montevideo: 6
Madrid: 8
Sao Paulo: 8


In [16]:
#--------------
# Radius
#--------------
capitals={'CABA': caba_G, 'CDMX':cdmx_G, 'Santiago de Chile': scl_G, 'Montevideo': mtv_G, 'Madrid': mad_G, 'Sao Paulo': sao_G}

#parece que la eccentricidad de cualquier nodo en las redes dirigidas es infinito, 
#por lo que vamos a tornar no dirigidas todas esas redes
for city,graph in capitals.items():
    for i in range(len(nx.nodes(graph))):
        try:
            print(nx.eccentricity(graph,i))
        except:
            None

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.radius(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: 3
CDMX: 4
Santiago de Chile: 3
Montevideo: 3
Madrid: 5
Sao Paulo: 4


In [36]:
capitals = {'CABA': caba_sin_islas, 'CDMX':cdmx_sin_islas, 'Santiago de Chile': scl_sin_islas, 'Montevideo': mtv_sin_islas, 'Madrid': mad_sin_islas, 'Sao Paulo': sao_sin_islas}

#las columnas que vamos a aregar al DataFrame
diameter = [0]*len(capitals)
radius = [0]*len(capitals)
avg_shortest_path_length = [0]*len(capitals)
transitivity = [0]*len(capitals)
global_efficiency = [0]*len(capitals)
modularity = [0]*len(capitals)

small_worldness = [0]*len(capitals)


for city, graph in capitals.items():
    city_index=df_concat.index[df_concat['Ciudad']==city].tolist()[0]
    
    #conseguimos cada parámetro para esta ciudad
    undirected=nx.to_undirected(graph)
    diameter[city_index] =                     nx.diameter(undirected)
    radius[city_index] =                       nx.radius(undirected)
    avg_shortest_path_length[city_index] =     nx.average_shortest_path_length(undirected)
    transitivity[city_index] =                 nx.transitivity(undirected)
    global_efficiency[city_index] =            nx.global_efficiency(undirected)
    small_worldness[city_index] =              nx.nx.algorithms.smallworld.sigma(graph.to_undirected(),niter=1,nrand=5)

    
    #espacio para modularidad
    
    #deg_assortativity_coefficient[city_index]= nx.degree_assortativity_coefficient(undirected)
    
df_concat['Diámetro'] = diameter
df_concat['Radio'] = radius
df_concat['Camino más corto promedio'] = avg_shortest_path_length
df_concat['Transitividad'] = transitivity
df_concat['Eficiencia Global'] = global_efficiency
#df_concat['Coeficiente de Asortatividad de Grado'] = deg_assortativity_coefficient
df_concat['Small Worldness']= small_worldness
df_concat

Ciudad       País  timeset        d1  indegree  outdegree  \
0               CABA  Argentina      NaN  2.279646  3.088496   3.088496   
1               CDMX     México      NaN  2.307936  2.611111   2.611111   
2  Santiago de Chile      Chile      NaN  2.404762  2.928571   2.928571   
3         Montevideo    Uruguay      NaN  4.348214  5.232143   5.232143   
4             Madrid     España      NaN  2.118095  2.733333   2.733333   
5          Sao Paulo     Brasil      NaN  1.973626  2.362637   2.362637   

      Degree  weighted indegree  weighted outdegree  Weighted Degree  \
0   6.176991           3.088496            3.088496         6.176991   
1   5.222222           2.611111            2.611111         5.222222   
2   5.857143                NaN                 NaN              NaN   
3  10.464286                NaN                 NaN              NaN   
4   5.466667           2.733333            2.733333         5.466667   
5   4.725275                NaN                 NaN              NaN   

   Eccentricity  clustering  Diámetro  Radio  Camino más corto promedio  \
0      3.884956         NaN         5      3                   2.695638   
1      3.619048    0.110592         6      3                   3.020952   
2      3.809524    0.220837         5      3                   2.591509   
3      4.267857    0.237409         5      3                   2.454955   
4      5.047619    0.187666         5      3                   2.915385   
5      3.824176    0.244116         6      4                   3.195849   

   Transitividad  Eficiencia Global  Small Worldness  
0       0.153442           0.412624         1.054803  
1       0.100939           0.371892         1.103744  
2       0.177891           0.433281         1.159745  
3       0.260311           0.458451         1.166953  
4       0.136833           0.388462         1.144773  
5       0.142139           0.362336         1.271280

In [37]:
df_concat.to_csv('Tidy_DataFrame_sin_islas.csv',index=False)

In [19]:
#Obsevación (no sé muy ien que hacer aquí):
#parece que aunque las graficas dirigidas no sean conexas, el camino 
#más corto promedio si se está pudiendo computar, y nos da un resultado.. menor?

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.average_shortest_path_length(graph)))
        print(city+str(': ')+str(nx.average_shortest_path_length(nx.to_undirected(graph))))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))

CABA: 1.0389520055645722
CABA: 3.355668907952701

CDMX: 0.9519539404278243
CDMX: 3.82031828690714

Santiago de Chile: 1.1408141686492201
Santiago de Chile: 3.227544277028813

Montevideo: 1.5769881556683587
Montevideo: 3.0811157257857764

Madrid: 1.7462290355472734
Madrid: 3.7835167539819277

Sao Paulo: 0.865848406546081
Sao Paulo: 4.324031007751938



In [20]:
#mismo pasa con transitividad

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.transitivity(graph)))
        print(city+str(': ')+str(nx.transitivity(nx.to_undirected(graph))))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))

CABA: 0.04529683885890517
CABA: 0.10739164086687307

CDMX: 0.016150740242261104
CDMX: 0.05

Santiago de Chile: 0.04595959595959596
Santiago de Chile: 0.10074358359318782

Montevideo: 0.13019250253292808
Montevideo: 0.22452327250358828

Madrid: 0.04256080114449213
Madrid: 0.08191653786707882

Sao Paulo: 0.026829268292682926
Sao Paulo: 0.07857142857142857



In [21]:
#eficiencia global solo esta definida para las versiones no dirigidas de nuestras redes

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.global_efficiency(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))

print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.global_efficiency(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf

***

CABA: 0.32577285725335
CDMX: 0.28932026537809863
Santiago de Chile: 0.3388888888889442
Montevideo: 0.3608367943394337
Madrid: 0.29465342622415475
Sao Paulo: 0.266719012755837


In [22]:
#modularidad no está definido?

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.modularity(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))
        
print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.community.modularity(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf

***

CABA: inf
CDMX: inf
Santiago de Chile: inf
Montevideo: inf
Madrid: inf
Sao Paulo: inf


In [23]:
#Assortativity coefficient

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.degree_assortativity_coefficient(graph)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))
        
print('')
print('***')
print('')

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.degree_assortativity_coefficient(nx.to_undirected(graph))))
    except:
        print(city+str(': ')+str(float('inf')))

CABA: -0.14027483483281894

CDMX: -0.2260240428366605

Santiago de Chile: -0.20519093988322598

Montevideo: -0.02413444189375622

Madrid: -0.23122324687720558

Sao Paulo: -0.18368170666113665


***

CABA: -0.2539782482426901
CDMX: -0.43889050792093515
Santiago de Chile: -0.27799460336687964
Montevideo: -0.06425865639772806
Madrid: -0.3000957821604226
Sao Paulo: -0.45871333872295067


In [24]:
# Small Worldness
#networkx.algorithms.smallworld.random_reference

for city, graph in capitals.items():
    try:
        print(city+str(': ')+str(nx.algorithms.smallworld.sigma(graph.to_undirected(),niter=1,nrand=2)))
        print('')
    except:
        print(city+str(': ')+str(float('inf')))
        
print('')
print('***')
print('')
"""
for city, graph in capitals.items():
    try:
        undirected=nx.to_undirected(graph)
        ref=nx.smallworld.random_reference(undirected)
        
        #clustering coefficient ratio
        cluster_und=nx.clustering_coefficient(undirected)
        cluster_ref=nx.clustering_coefficient(ref)
        cluster_ratio=cluster_und/cluster_ref
        
        #characteristic path length ratio
        cpl_und=nx.average_shortest_path_length(undirected)
        cpl_ref=nx.average_shortest_path_length(ref)
        cpl_ratio=cpl_und/cpl_ref
        
        print(city+str(': ')+str(cluster_ratio/cpl_ratio))
    except:
        print(city+str(': ')+str(float('inf')))
"""

#hmm creo que aqui ya no supe muy bien como utilizar el grafo de referencia
#haré un intento más y si quieres ya te voy a pasar el código, Kevin

CABA: 0.9779832522694489

CDMX: 0.7892041780783782

Santiago de Chile: 1.0180289257370956

Montevideo: 1.254563347284867

Madrid: 0.990780366636198

Sao Paulo: 1.2190755533212827


***



"\nfor city, graph in capitals.items():\n    try:\n        undirected=nx.to_undirected(graph)\n        ref=nx.smallworld.random_reference(undirected)\n        \n        #clustering coefficient ratio\n        cluster_und=nx.clustering_coefficient(undirected)\n        cluster_ref=nx.clustering_coefficient(ref)\n        cluster_ratio=cluster_und/cluster_ref\n        \n        #characteristic path length ratio\n        cpl_und=nx.average_shortest_path_length(undirected)\n        cpl_ref=nx.average_shortest_path_length(ref)\n        cpl_ratio=cpl_und/cpl_ref\n        \n        print(city+str(': ')+str(cluster_ratio/cpl_ratio))\n    except:\n        print(city+str(': ')+str(float('inf')))\n"

In [28]:
#Cambiar los nombres de los atributos del DataFrame
#algunos nombres de columnas no fueron modificados para facilitar legibilidad
df_concat.rename(columns={'mentions': 'Menciones', 'Eccentricity': 'Eccentricidad', 'clustering':'Clustering'}, inplace=True)
df_concat

Ciudad       País  Menciones  avg strength    weight  indegree  \
0               CABA  Argentina   2.285088      3.244633  1.481579  2.192982   
1               CDMX     México        NaN      3.477388  1.388629  1.829431   
2  Santiago de Chile      Chile   2.097436      3.417211  1.462564  1.974359   
3         Montevideo    Uruguay   4.065657      3.227742  2.749495  3.873737   
4             Madrid     España   1.958159      3.518387  1.362343  1.895397   
5          Sao Paulo     Brasil   1.800926      3.430669  1.253704  1.685185   

   outdegree    Degree  weighted indegree  weighted outdegree  \
0   2.192982  4.385965           7.008772            7.008772   
1   1.829431  3.658863           6.481605            6.481605   
2   1.974359  3.948718           6.882051            6.882051   
3   3.873737  7.747475          12.969697           12.969697   
4   1.895397  3.790795           6.430962            6.430962   
5   1.685185  3.370370           5.847222            5.847222   

   Weighted Degree  Eccentricidad  Clustering  Diámetro  Radio  \
0        14.017544       4.798246    0.148791         6      3   
1        12.963211       5.622074    0.075940         7      4   
2        13.764103       5.041026    0.134037         6      3   
3        25.939394       4.479798    0.207747         6      3   
4        12.861925       6.079498    0.120510         8      5   
5        11.694444       6.726852    0.129928         8      4   

   Camino más corto promedio  Transitividad  Eficiencia Global  \
0                   3.355669       0.107392           0.325773   
1                   3.820318       0.050000           0.289320   
2                   3.227544       0.100744           0.338889   
3                   3.081116       0.224523           0.360837   
4                   3.783517       0.081917           0.294653   
5                   4.324031       0.078571           0.266719   

   Small Worldness  
0         1.019211  
1         0.773923  
2         0.993801  
3         1.261690  
4         1.034848  
5         1.158322

In [32]:
#-----------------
#  Modularidades
#-----------------
#     Estas medidas fueron tomadas no por medio de este programa, sino manualmente desde el programa Gephi
#     Metodología:
#        Tomamos tres medidas en cada red, con cada una de las resoluciones 0.8, 1.0, 1.2, con o sin ejes
#
#        Network       (CABA, CDMX, MAD, MTV SAO, SCL)
#        Resolution    (0.8, 1.0, 1.2)  
#        Edge weights  (Y/N)
#        
#        Y luego de ello tomamos la mediana de las tres medidas de resolución, a modo de tomar en cuenta variabilidad




df_concat['Modularidad con pesos (0.8)'] = [0.402, 0.484, 0.530, 0.472, 0.611, 0.686]
df_concat['Modularidad con pesos (1.0)'] = [0.524, 0.628, 0.530, 0.611, 0.610, 0.682]
df_concat['Modularidad con pesos (1.2)'] = [0.654, 0.776, 0.524, 0.756, 0.612, 0.673]


df_concat['Modularidad sin pesos (0.8)'] = [0.497, 0.602, 0.496, 0.353, 0.568, 0.673]
df_concat['Modularidad sin pesos (1.0)'] = [0.493, 0.604, 0.500, 0.348, 0.572, 0.664]
df_concat['Modularidad sin pesos (1.2)'] = [0.499, 0.601, 0.505, 0.337, 0.563, 0.661]

df_concat

Ciudad       País  Menciones  avg strength    weight  indegree  \
0               CABA  Argentina   2.285088      3.244633  1.481579  2.192982   
1               CDMX     México        NaN      3.477388  1.388629  1.829431   
2  Santiago de Chile      Chile   2.097436      3.417211  1.462564  1.974359   
3         Montevideo    Uruguay   4.065657      3.227742  2.749495  3.873737   
4             Madrid     España   1.958159      3.518387  1.362343  1.895397   
5          Sao Paulo     Brasil   1.800926      3.430669  1.253704  1.685185   

   outdegree    Degree  weighted indegree  weighted outdegree  ...  \
0   2.192982  4.385965           7.008772            7.008772  ...   
1   1.829431  3.658863           6.481605            6.481605  ...   
2   1.974359  3.948718           6.882051            6.882051  ...   
3   3.873737  7.747475          12.969697           12.969697  ...   
4   1.895397  3.790795           6.430962            6.430962  ...   
5   1.685185  3.370370           5.847222            5.847222  ...   

   Camino más corto promedio  Transitividad  Eficiencia Global  \
0                   3.355669       0.107392           0.325773   
1                   3.820318       0.050000           0.289320   
2                   3.227544       0.100744           0.338889   
3                   3.081116       0.224523           0.360837   
4                   3.783517       0.081917           0.294653   
5                   4.324031       0.078571           0.266719   

   Small Worldness  Modularidad con pesos (0.8)  Modularidad con pesos (1.0)  \
0         1.019211                        0.402                        0.524   
1         0.773923                        0.484                        0.628   
2         0.993801                        0.530                        0.530   
3         1.261690                        0.472                        0.611   
4         1.034848                        0.611                        0.610   
5         1.158322                        0.686                        0.682   

   Modularidad con pesos (1.2)  Modularidad sin pesos (0.8)  \
0                        0.654                        0.497   
1                        0.776                        0.602   
2                        0.524                        0.496   
3                        0.756                        0.353   
4                        0.612                        0.568   
5                        0.673                        0.673   

   Modularidad sin pesos (1.0)  Modularidad sin pesos (1.2)  
0                        0.493                        0.499  
1                        0.604                        0.601  
2                        0.500                        0.505  
3                        0.348                        0.337  
4                        0.572                        0.563  
5                        0.664                        0.661  

[6 rows x 25 columns]