In [8]:
import pandas as pd
import numpy as np 
import networkx as nx
import scipy.stats as stats

ags_nd=pd.read_csv('Gephi_stats/Gephi AGS Stats.csv')
caba_nd=pd.read_csv('Gephi_stats/Gephi CABA Stats.csv')
cdmx_nd=pd.read_csv('Gephi_stats/Gephi CDMX Stats.csv')
gdl_nd=pd.read_csv('Gephi_stats/Gephi GDL Stats.csv')
hgo_nd=pd.read_csv('Gephi_stats/Gephi Hidalgo Stats.csv')
mad_nd=pd.read_csv('Gephi_stats/Gephi Madrid Stats.csv')
mtv_nd=pd.read_csv('Gephi_stats/Gephi Montevideo Stats.csv')
oax_nd=pd.read_csv('Gephi_stats/Gephi Oaxaca Stats.csv')
sao_nd=pd.read_csv('Gephi_stats/Gephi Sao Paulo Stats.csv')
scl_nd=pd.read_csv('Gephi_stats/Gephi SCL Stats.csv')

ags_ed=pd.read_csv('Gephi_edges/Gephi AGS Edges.csv')
caba_ed=pd.read_csv('Gephi_edges/Gephi CABA Edges.csv')
cdmx_ed=pd.read_csv('Gephi_edges/Gephi CDMX Edges.csv')
gdl_ed=pd.read_csv('Gephi_edges/Gephi GDL Edges.csv')
hgo_ed=pd.read_csv('Gephi_edges/Gephi Hidalgo Edges.csv')
mad_ed=pd.read_csv('Gephi_edges/Gephi Madrid Edges.csv')
mtv_ed=pd.read_csv('Gephi_edges/Gephi Montevideo Edges.csv')
oax_ed=pd.read_csv('Gephi_edges/Gephi Oaxaca Edges.csv')
sao_ed=pd.read_csv('Gephi_edges/Gephi Sao Paulo Edges.csv')
scl_ed=pd.read_csv('Gephi_edges/Gephi SCL Edges.csv')

In [10]:
def armar_grafo(nodes,edges,rol_str,weight_str):
    G=nx.from_pandas_edgelist(edges,'Source','Target',edge_attr=["Weight"],create_using=nx.DiGraph())
    rol = {nid: nodes[nodes['Id']==nid][rol_str].values[0] for nid in nodes['Id']}
    nx.set_node_attributes(G,rol,'rol')
    weight = {nid: nodes[nodes['Id']==nid][weight_str].values[0] for nid in nodes['Id']}
    nx.set_node_attributes(G,weight,'weight')
    return G

ags_G=armar_grafo(ags_nd,ags_ed,'role','weight')
caba_G=armar_grafo(caba_nd,caba_ed,'type','weight')
cdmx_G=armar_grafo(cdmx_nd,cdmx_ed,'rol estimado','weight')
gdl_G=armar_grafo(gdl_nd,gdl_ed,'type','weight')
hgo_G=armar_grafo(hgo_nd,hgo_ed,'type','weight')
mad_G=armar_grafo(mad_nd,mad_ed,'rol estimado','weight')
mtv_G=armar_grafo(mtv_nd,mtv_ed,'rol estimado','node size')
oax_G=armar_grafo(oax_nd,oax_ed,'rol','weight')
sao_G=armar_grafo(sao_nd,sao_ed,'rol estimado','weight')
scl_G=armar_grafo(scl_nd,scl_ed,'type','weight')

In [12]:
print(nx.attribute_mixing_matrix(caba_G,'rol',mapping={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}))
print(nx.attribute_mixing_matrix(cdmx_G,'rol',mapping={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}))
print(nx.attribute_mixing_matrix(scl_G,'rol',mapping={'Generador de Conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}))

[[0.01508621 0.0387931  0.00862069 0.01724138 0.04741379 0.        ]
 [0.05603448 0.31896552 0.01077586 0.06896552 0.12715517 0.01939655]
 [0.         0.         0.         0.         0.         0.        ]
 [0.00431034 0.05603448 0.00431034 0.03017241 0.0237069  0.01077586]
 [0.01724138 0.05603448 0.         0.01508621 0.03232759 0.        ]
 [0.00215517 0.01508621 0.         0.         0.00431034 0.        ]]
[[0.00398406 0.02390438 0.00199203 0.00199203 0.01195219 0.        ]
 [0.03784861 0.51394422 0.02390438 0.06772908 0.10956175 0.02788845]
 [0.00199203 0.02191235 0.00398406 0.         0.         0.        ]
 [0.00199203 0.02988048 0.         0.00199203 0.00398406 0.00199203]
 [0.00199203 0.01992032 0.         0.00199203 0.00796813 0.00398406]
 [0.         0.05179283 0.0059761  0.0059761  0.00398406 0.00398406]]
[[0.0140056  0.10084034 0.00840336 0.0280112  0.06442577 0.00280112]
 [0.03641457 0.26610644 0.00560224 0.04201681 0.07282913 0.00840336]
 [0.         0.00840336 0.      

In [11]:
caba_core=nx.k_core(caba_G,k=3)
cdmx_core=nx.k_core(cdmx_G,k=3)
scl_core=nx.k_core(scl_G,k=3)
mad_core=nx.k_core(mad_G,k=3)
mtv_core=nx.k_core(mtv_G,k=3)
sao_core=nx.k_core(sao_G,k=3)

nx.write_graphml(caba_core,'Gephi_core/CABA core graph.graphml')
nx.write_graphml(cdmx_core,'Gephi_core/CDMX core graph.graphml')
nx.write_graphml(scl_core,'Gephi_core/Scl core graph.graphml')
nx.write_graphml(mad_core,'Gephi_core/Mad core graph.graphml')
nx.write_graphml(mtv_core,'Gephi_core/Mtv core graph.graphml')
nx.write_graphml(sao_core,'Gephi_core/Sao core graph.graphml')

caba_crust=nx.k_crust(caba_G,k=3)
cdmx_crust=nx.k_crust(cdmx_G,k=3)
scl_crust=nx.k_crust(scl_G,k=3)
mad_crust=nx.k_crust(mad_G,k=3)
mtv_crust=nx.k_crust(mtv_G,k=3)
sao_crust=nx.k_crust(sao_G,k=3)

nx.write_graphml(caba_crust,'Gephi_crust/CABA crust graph.graphml')
nx.write_graphml(cdmx_crust,'Gephi_crust/CDMX crust graph.graphml')
nx.write_graphml(scl_crust,'Gephi_crust/Scl crust graph.graphml')
nx.write_graphml(mad_crust,'Gephi_crust/Mad crust graph.graphml')
nx.write_graphml(mtv_crust,'Gephi_crust/Mtv crust graph.graphml')
nx.write_graphml(sao_crust,'Gephi_crust/Sao crust graph.graphml')

In [13]:
print(nx.attribute_mixing_matrix(caba_core,'rol',mapping={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}))
print(nx.attribute_mixing_matrix(cdmx_core,'rol',mapping={'Generador de conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}))
print(nx.attribute_mixing_matrix(scl_core,'rol',mapping={'Generador de Conocimiento':0,'Habilitador':1,'Promotor':2,'Vinculador':3,'Articulador':4,'Comunidad':5}))

[[0.004 0.028 0.004 0.016 0.06  0.   ]
 [0.032 0.276 0.008 0.08  0.192 0.   ]
 [0.    0.    0.    0.    0.    0.   ]
 [0.    0.068 0.    0.024 0.032 0.004]
 [0.016 0.084 0.    0.016 0.044 0.   ]
 [0.004 0.004 0.    0.    0.004 0.   ]]
[[0.         0.04694836 0.         0.         0.02816901 0.        ]
 [0.03755869 0.49765258 0.         0.05633803 0.14084507 0.03286385]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.03286385 0.         0.         0.00469484 0.        ]
 [0.00469484 0.02816901 0.         0.00469484 0.00938967 0.00469484]
 [0.         0.05633803 0.         0.00469484 0.00469484 0.00469484]]
[[0.01129944 0.10734463 0.         0.02824859 0.10169492 0.        ]
 [0.03389831 0.23728814 0.         0.05084746 0.11299435 0.00564972]
 [0.         0.         0.         0.         0.         0.        ]
 [0.01694915 0.07909605 0.         0.00564972 0.02824859 0.        ]
 [0.01694915 0.08474576 0.         0.         0.05084746 0.        ]
 [0.0

In [19]:
caba_avg=caba_nd.mean()
cdmx_avg=cdmx_nd.mean()
scl_avg=scl_nd.mean()
mad_avg=mad_nd.mean()
mtv_avg=mtv_nd.mean()
sao_avg=sao_nd.mean()

In [20]:
print(caba_avg)

timeset                              NaN
mentions                        2.285088
avg strength                    3.244633
weight                          1.481579
indegree                        2.192982
outdegree                       2.192982
Degree                          4.385965
weighted indegree               7.008772
weighted outdegree              7.008772
Weighted Degree                14.017544
Eccentricity                    4.798246
closnesscentrality              0.303853
harmonicclosnesscentrality      0.325773
betweenesscentrality          267.368421
modularity_class                5.850877
Authority                       0.036946
Hub                             0.036946
componentnumber                 0.000000
strongcompnum                  96.763158
clustering                      0.148791
triangles                       2.434211
eigencentrality                 0.093111
dtype: float64
